export { default as Logo } from './dailydevstudio.png'
export { default as Header_bg } from './header_bg.svg'
export { default as Header_fg } from './header_fg.svg'
export { default as work_together } from './work_together.svg'
export { default as Project1 } from './project1.png'
export { default as Project2 } from './project2.png'
export { default as Project3 } from './project3.png'
export { default as Project4 } from './project4.png'
export { default as Project5 } from './project5.png'
export { default as Project6 } from './project6.png'
export { default as Project7 } from './project7.png'
export { default as Project8 } from './project8.png'

export { default as person1 } from './person1.jpeg'
export { default as person2 } from './person2.jpeg'
export { default as person3 } from './person3.jpeg'
export { default as person4 } from './person4.jpeg' 